### ISSUE TITLE
password of futurerestore

### ISSUE THREAD

**Issue by riverinem** [LukeZGD/32bit-OTA-Downgrader#10]
hi, dude, could you tell me which password it is, both alpine or my mac password are failed;
`[Log] Found device in DFU mode.

[Log] Extracting IPSW...
[Log] Preparing for futurerestore (starting local server)...
[Log] Will now proceed to futurerestore...

Password:
Sorry, try again.
Password:

Sorry, try again.
Password:
sudo: 3 incorrect password attempts
`

**Comment by LukeZGD** [comment]
Please refer to [this page regarding sudo](https://support.apple.com/en-us/HT202035)
