### ISSUE TITLE
Not working on iPad3,5, iPad3,6

### ISSUE THREAD

**Issue by arumia** [LukeZGD/32bit-OTA-Downgrader#11]
After entering recovery mode, a green screen appears on the iPad and the following error does not proceed.

lubuntu 18.04 on vm, liveusb have same problem

Thank you!

Here is the full log
`******* 32bit-OTA-Downgrader *******
    Downgrade script by LukeZGD     

Main Menu

HardwareModel: P103AP
ProductType: iPad3,6
ProductVersion: 10.3.4
UniqueChipID (ECID): 4003647939537

[Input] Select an option:
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) Exit
3) Just put device in kDFU mode
#? 1
Select iOS version:
1) iOS 8.4.1
2) Other
3) Back
#? 1
iOS 8.4.1 Downgrade
[Log] Firmware keys missing, downloading firmware keys...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135  100   135    0     0    227      0 --:--:-- --:--:-- --:--:--   227
100 70542    0 70542    0     0  64304      0 --:--:--  0:00:01 --:--:--  407k
[Log] Downloading ota.json...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34.8M    0 34.8M    0     0  1913k      0 --:--:--  0:00:18 --:--:--  665k
[Log] Copying ota.json to tmp...
[Log] Saving 8.4.1 blobs with tsschecker...
Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[TSSC] manually specified ecid to use, parsed "4003647939537" to dec:4003647939537 hex:3a42c0363d1
[TSSC] opening resources/manifests/BuildManifest_iPad3,6_8.4.1.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!

iOS 8.4.1 for device iPad3,6 IS being signed!
[Log] Verifying IPSW...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    40    0    40    0     0     32      0 --:--:--  0:00:01 --:--:--    32
[Log] Extracting iBSS from IPSW...
Archive:  iPad3,6_8.4.1_12H321_Restore.ipsw
  inflating: tmp/iBSS.p103.RELEASE.dfu  
[Log] Decrypting iBSS...
IV = 1d99e780d96c32a25ca7e4b1c7fe14c0
Key = 4e2c14927693d61e1da375e340061521c9376007163f6ab55afbe1a03b901fd3
/home/tihm/odysseusOTA/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: c70b425a6aa48d0235d3e54397f5a5e6233eb28270e6e4f0189d05256e52b48c3af93353b32abb5deada325a84176d63
/home/tihm/odysseusOTA/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: c70b425a6aa48d0235d3e54397f5a5e6233eb28270e6e4f0189d05256e52b48c3af93353b32abb5deada325a84176d63
/home/tihm/odysseusOTA/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: c70b425a6aa48d0235d3e54397f5a5e6233eb28270e6e4f0189d05256e52b48c3af93353b32abb5deada325a84176d63
1218+1 records in
1218+1 records out
77980 bytes (78 kB, 76 KiB) copied, 0.00440757 s, 17.7 MB/s
[Log] Patching iBSS...
[Log] Mounting device with ifuse...
[Log] Copying stuff to device...
[Log] Unmounting device...

[Log] Open MTerminal and run these commands:

$ su
(enter root password, default is 'alpine')
# cd Media
# chmod +x pwn.sh
# ./pwn.sh

Press home/power button once when screen goes black on the device
[Log] Finding device in DFU mode...
[Log] Found device in DFU mode.
[Log] Extracting IPSW...
[Log] Preparing for futurerestore (starting local server)...
[Log] Proceeding to futurerestore...
Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152
Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44
Odysseus Support: yes
[INFO] 32bit device detected
futurerestore init done
reading ticket 4003647939537_iPad3,6_8.4.1-12H321_c65de6350551ab4934cd986df22a30843dd43948.shsh2 done
user specified to use latest signed baseband (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
Serving HTTP on 0.0.0.0 port 80 (http://0.0.0.0:80/) ...
[TSSC] selecting latest iOS: 10.3.4
[TSSC] got firmwareurl for iOS 10.3.4 build 14G61
100 [===================================================================================================>]
downloading Baseband
100 [===================================================================================================>]
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening /tmp/futurerestore/basebandManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as p103ap, iPad3,6
Extracting BuildManifest from IPSW
Product Version: 8.4.1
Product Build: 12H321 Major: 12
Device supports Image4: false
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[WARNING] skipping ramdisk hash check, since device is in pwnDFU according to user
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
127.0.0.1 - - [21/Mar/2020 18:29:27] "GET /firmware/iPad3,6/12H321 HTTP/1.1" 301 -
127.0.0.1 - - [21/Mar/2020 18:29:27] "GET /firmware/iPad3,6/12H321/ HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2020 18:29:27] "GET /firmware/iPad3,6/12H321 HTTP/1.1" 301 -
127.0.0.1 - - [21/Mar/2020 18:29:27] "GET /firmware/iPad3,6/12H321/ HTTP/1.0" 200 -
Extracting iBSS.p103.RELEASE.dfu...
iBoot32Patch: iBoot-2261 inputted.
patch_rsa_check: Entering...
find_bl_verify_shsh_generic: Entering...
find_bl_verify_shsh_generic: Found LDR instruction at 0x663c
find_bl_verify_shsh_generic: Found BL verify_shsh at 0x69e2
find_bl_verify_shsh_generic: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x69e2...
patch_rsa_check: Leaving...
iBoot32Patch: Quitting...
Extracting iBEC.p103.RELEASE.dfu...
iBoot32Patch: iBoot-2261 inputted.
patch_ticket_check: Entering...
patch_ticket_check: Found iBoot baseaddr 0xbff00000
patch_ticket_check: Found iboot_vers_str at 0x280
patch_ticket_check: Found str_pointer at 0x308
patch_ticket_check: Found iboot_str_3_xref at 0x2029c
patch_ticket_check: Found ldr_intruction at 0x20208
patch_ticket_check: Found last_good_bl at 0x20210...
patch_ticket_check: Found next_pop at 0x2028e...
patch_ticket_check: Found next_pop at 0xbff2028e...
patch_ticket_check: Found last_branch at 0x20282...
patch_ticket_check: Patching in mov.w r0, #0 at 0x20214...
patch_ticket_check: Patching in mov.w r1, #0 at 0x20218...
patch_ticket_check: NOPing useless stuff at 0x2021c to 0x20284 ...
patch_ticket_check: Leaving...
patch_rsa_check: Entering...
find_bl_verify_shsh_generic: Entering...
find_bl_verify_shsh_generic: Found LDR instruction at 0x1bbf4
find_bl_verify_shsh_generic: Found BL verify_shsh at 0x1c22e
find_bl_verify_shsh_generic: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x1c22e...
patch_rsa_check: Leaving...
iBoot32Patch: Quitting...
Sending iBSS (78044 bytes)...
[==================================================] 100.0%
Sending iBEC (295132 bytes)...
[==================================================] 100.0%
INFO: device serial number is DMPJTDSNF18W
Using cached filesystem from 'iPad3,6_8.4.1_12H321_Restore/058-24407-023.dmg'
Sending APTicket (2742 bytes)

Getting ApNonce in recovery mode... 45 44 78 a5 27 45 56 14 53 60 13 2b 9b 78 46 b1 d1 d0 e2 97 
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Sending APTicket (2742 bytes)
Recovery Mode Environment:
iBoot build-version=iBoot-2261.30.37
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~ipad.s5l8955x.img3...
127.0.0.1 - - [21/Mar/2020 18:29:53] "GET /firmware/iPad3,6/12H321 HTTP/1.1" 301 -
127.0.0.1 - - [21/Mar/2020 18:29:53] "GET /firmware/iPad3,6/12H321/ HTTP/1.0" 200 -
[Error] ERROR: libipatcher failed with reason IV has bad length. Expected=16 actual=0. Got IV=
Done: restoring failed.
Failed with errorcode=377

[Log] futurerestore done!
You can choose to retry if futurerestore failed on downloading baseband or for some other reason
[Input] Retry? (y/N) 
`

**Comment by LukeZGD** [comment]
I see, missing firmware keys problem is present on iPad3,6 as well, also affects iPad3,5

**Comment by LukeZGD** [comment]
Please try again with the latest commit, I fixed the missing keys now and hopefully they work

**Comment by arumia** [comment]
It's well done!
