### ISSUE TITLE
Down for me or for everyone ?

### ISSUE THREAD

**Issue by prynhart** [LukeZGD/32bit-OTA-Downgrader#12]
I hope it's just me doing something wrong :'(.  Trying to downgrade an iPad 2,2 here so that it runs so much nicer under iOS 6 (rather than iOS 9) and am getting (on Ubuntu 18.04 LTS)

$ ./restore.sh 

******* 32bit-OTA-Downgrader *******
    Downgrade script by LukeZGD     

Main Menu

HardwareModel: K94AP
ProductType: iPad2,2
ProductVersion: 9.3.5
UniqueChipID (ECID): 2427730887500

[Input] Select an option:
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) Exit
3) Just put device in kDFU mode
#? 2
[Input] Select iOS version:
1) iOS 8.4.1
2) iOS 6.1.3
3) Back
#? 2
iOS 6.1.3 SaveOTABlobs
[Log] Saving 6.1.3 blobs with tsschecker...
Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[TSSC] manually specified ecid to use, parsed "2427730887500" to dec:2427730887500 hex:2354009834c
[TSSC] opening resources/manifests/BuildManifest_iPad2,2_6.1.3.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure

iOS 6.1.3 for device iPad2,2 IS NOT being signed!
ls: cannot access '2427730887500_iPad2,2_6.1.3-*.shsh2': No such file or directory
[Error] Saving 6.1.3 blobs failed. Please run the script again

**Comment by LukeZGD** [comment]
I just tested, iPad2,1 and 2,3 worked but not 2,2.. This is pretty weird, I'll check into it more later

**Comment by prynhart** [comment]
Thank you @LukeZGD for the quick response.  It is possible that I'm doing something wrong hence the query as to whether it's just me (or all!).  Pleased to hear 2,1 and 2,3 are good because it makes it more likely that it's a fault on my end.

**Comment by prynhart** [comment]
@LukeZGD - Just wanted to comment:

1. I love your work :-)
2. I successfully downgraded a device from iOS 9.3.5 to 6.1.3 on the same Linux host recently (it was the 8th of March 2020), but that was a iPad2,1. 

Have just double checked that the iPad2,2 is properly jailbroken (i.e. the Phoenix app reports "Your iPad2,2 is jailbroken) and also have root via SSH, i.e.

# uname -a
Darwin Patricks-iPad 15.6.0 Darwin Kernel Version 15.6.0: Fri Aug 19 10:37:54 PDT 2016; root:xnu-3248.61.1~1/MarijuanARM_S5L8940X iPad2,2 arm K94AP Darwin

With Thanks again

Patrick

**Comment by LukeZGD** [comment]
I checked the signing status using tsschecker, and it seems that Apple has unsigned iOS 6.1.3 for iPad2,2 now.. iOS 8.4.1 downgrades are still an option though

**Comment by prynhart** [comment]
Aww - that's a pity.  I love iOS 6 on these devices.  (Boo!  Apple should let us run what we'd like.)

Thank you so much for all your efforts with this project, it really helps - you've put together a great toolset for those of us who think that upgrades aren't always an upgrade.

**Comment by prynhart** [comment]
> I checked the signing status using tsschecker, and it seems that Apple has unsigned iOS 6.1.3 for iPad2,2 now.. iOS 8.4.1 downgrades are still an option though

Ugh - now they've disabled signing for iOS 8.4.1 on the iPad2,2.  I wonder what Apple have against this particular model :-)
