### ISSUE TITLE
Getting keys failed error

### ISSUE THREAD

**Issue by xstecky** [LukeZGD/32bit-OTA-Downgrader#14]
https://pastebin.com/b2JBjwZe

**Comment by LukeZGD** [comment]
I updated the iPhone5,1 firmware keys now, please try again

**Comment by xstecky** [comment]
The keys downloaded but getting a new error. https://pastebin.com/YSS3jL83

**Comment by LukeZGD** [comment]
I didn't notice the iBSS kbag was missing.. I updated the keys again

**Comment by xstecky** [comment]
Worked perfectly, thanks!
