### ISSUE TITLE
Sending iBEC freezes at 62.4%

### ISSUE THREAD

**Issue by swamprock** [LukeZGD/32bit-OTA-Downgrader#15]
I'm attempting a downgrade to iOS 6.1.3 from 9.3.5 on my iPad 2,1. Everything goes swimmingly until the script starts to send iBEC, where it freezes at 62.4%. I left it for about two hours before throwing in the towel. I tried a number of different things- different USB port, letting the script download the ipsw instead of supplying it- all with the same result. This was all done using a full install of Lubuntu 18.04, and a clean, jailbroken install of 9.3.5. Any guidance on this issue?

**Comment by LukeZGD** [comment]
Please share error logs and terminal output so I can look more into it

**Comment by swamprock** [comment]
Terminal output:
https://pastebin.com/9RWYp96u

Log:
https://pastebin.com/4bPNETbp

I attempted a downgrade to 8.4.1, and that froze at 61.2%. Weird.

**Comment by LukeZGD** [comment]
`OSError: [Errno 98] Address already in use` indicates that the local server is not starting properly as some other process is already using port 80, and I'm not really sure what it would be. Have you tried it on Manjaro live USB? I have tested the script there the most

**Comment by swamprock** [comment]
I'll give that a try. Funnily enough, I don't get the errors every time, and I've run the script countless times. The Phoenix jailbreak has to be obtained and applied using some pretty shady means these days, so that may have something to do with it (background processes, etc).

**Comment by msre13** [comment]
I see the same behaviour when trying to downgrade my iPad3,1. The device was reset to factory defaults. I've tested the script on macOS and two live distributions, Lubuntu and Manjaro. The iBEC transfer always freezes at 61.1%. To jailbrake the device I've used the official Phoenix version that I've signed myself. Here is a log: https://pastebin.com/raw/RXt5XTVJ. 

Any ideas on how to fix this?

**Comment by LukeZGD** [comment]
I suggest enter kDFU mode using kDFUApp (from repo.tihmstar.net) and run the script from there
