### ISSUE TITLE
macOS 10.13.6 loop

### ISSUE THREAD

**Issue by mikapietrus** [LukeZGD/32bit-OTA-Downgrader#18]
Hi, I'm trying to launch your script on macOS 10.13.6, every time I start restore.sh it's returning

******* 32bit-OTA-Downgrader *******
    Downgrade script by LukeZGD     

Install Dependencies
[Log] Installing dependencies for macOS with Homebrew...
Uninstalling /usr/local/Cellar/libusbmuxd/HEAD-5cbf763... (14 files, 165.0KB)
Uninstalling /usr/local/Cellar/libimobiledevice/HEAD-dc20b07_6... (70 files, 1.1MB)
Updating Homebrew...
==> Cloning https://github.com/libimobiledevice/libusbmuxd.git
Updating /Users/michal/Library/Caches/Homebrew/libusbmuxd--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 5cbf763 configure.ac: Drop AC_FUNC_MALLOC/REALLOC and use AC_CHECK_FUNCS instead to allow cross compiliation
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/libusbmuxd/HEAD-5cbf763
==> make install
🍺  /usr/local/Cellar/libusbmuxd/HEAD-5cbf763: 14 files, 165.0KB, built in 54 seconds
Updating Homebrew...
==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
Updating /Users/michal/Library/Caches/Homebrew/libimobiledevice--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at dc20b07 idevicesyslog: Add command line switch to exit when device disconnects
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/libimobiledevice/HEAD-dc20b07_6 --without-cython --enable-debug-code
==> make install
🍺  /usr/local/Cellar/libimobiledevice/HEAD-dc20b07_6: 70 files, 1.1MB, built in 1 minute 14 seconds
Updating Homebrew...
Warning: libzip 1.6.1 is already installed and up-to-date
To reinstall 1.6.1, run `brew reinstall libzip`
Warning: lsusb 1.0 is already installed and up-to-date
To reinstall 1.0, run `brew reinstall lsusb`
Updating Homebrew...
Warning: Cask 'osxfuse' is already installed.

To re-install osxfuse, run:
  brew cask reinstall osxfuse
Updating Homebrew...
Warning: ifuse 1.1.3 is already installed and up-to-date
To reinstall 1.1.3, run `brew reinstall ifuse`
[Log] Install script done! Please run the script again to proceed

next script run gives the same.

BTW. Downgrading to 6.1.3 with latest baseband  will give GPS work again on iPhone4S with 6.1.3?

**Comment by LukeZGD** [comment]
Try running`brew install python3`

**Comment by LukeZGD** [comment]
Updated dependency install
