### ISSUE TITLE
[Error] Cannot connect to device via SSH.

### ISSUE THREAD

**Issue by joyater** [LukeZGD/32bit-OTA-Downgrader#21]

**Comment by joyater** [comment]
it worked before idk what happened now i just want to connect

**Comment by LukeZGD** [comment]
Delete ~/.ssh/known_hosts and try again

**Comment by joyater** [comment]
I did delete earlier and when i navigate to ~/.ssh then known_hosts is not there. ill double check.....

**Comment by joyater** [comment]
nope its not there i deleted it i still have the error

**Comment by joyater** [comment]
do you know anything

**Comment by LukeZGD** [comment]
Not really sure, but your network may have LAN isolation, and may be the reason why the devices can't connect. That's not really on my end for me to fix

**Comment by joyater** [comment]
My network has restricted wifi cus my parents. should I request them to unrestrict it. maybe that's the cause..?
