### ISSUE TITLE
Tickets not saving properly

### ISSUE THREAD

**Issue by zapinator3000** [LukeZGD/32bit-OTA-Downgrader#22]
Blobs are no longer saving properly.
I have been able to manually save it and it work fine, but they're being saved in a different file name than what's being searched for. It seems as if apple is trying to prevent bots.
Correction:
It looks like you're trying to call based on the hex value, but it's being saved using the decimal of the ECID

**Comment by LukeZGD** [comment]
Just tested, blobs save properly, also being called with decimal as well, so this is a non-issue
