### ISSUE TITLE
Stuck at Waiting for device

### ISSUE THREAD

**Issue by zapinator3000** [LukeZGD/32bit-OTA-Downgrader#23]
Everything goes well until getting stuck at Waiting for device...
I do get the green screen and I get the restore loading bar, but nothing happens.
I'm running the script on:
 Ubuntu 19.10, Kernel 5.3.0-51
I'm trying to downgrade:
Ipad 2,4 to IOS 8.4.1 from IOS 9.3.5 on Pheonix Jailbreak

**Comment by LukeZGD** [comment]
Not sure what's going wrong there, it should go smoothly from that point.. You can try again on a different supported distro, also other USB cable or port

**Comment by zapinator3000** [comment]
> Not sure what's going wrong there, it should go smoothly from that point.. You can try again on a different supported distro, also other USB cable or port

Tested on a different distro, worked perfectly. No idea what happened there.

**Comment by TGC-TECH** [comment]
Sorry to comment on a closed issue but I am having the exact same issue on Ubuntu 20.04 - what distro ended up working for you?

**Comment by zapinator3000** [comment]
> Sorry to comment on a closed issue but I am having the exact same issue on Ubuntu 20.04 - what distro ended up working for you?
XUbuntu 20.04 worked for me. Sorry for taking so long to respond. Hopefully you found something that worked!
