### ISSUE TITLE
Sending iBEC stuck at 65.1%

### ISSUE THREAD

**Issue by federicochiesa** [LukeZGD/32bit-OTA-Downgrader#24]
I'm trying to downgrade an iPhone 4S to 6.1.3 on macOS 10.14.6 and the process gets stuck there. 
One thing I did is when it said "Press home/power button once when screen goes black on the device" it didn't work, so I held both buttons, and after a while released the power button, and then it detected it. I hope that's not the problem. If needed I can provide the terminal output.

**Comment by LukeZGD** [comment]
That's not kDFU mode but regular kDFU mode, so that will fail to restore.. I suggest reboot and try again, or alternatively, enter kDFU mode using kDFUApp (from repo.tihmstar.net) and run the script from there

**Comment by federicochiesa** [comment]
That was the problem, I went into kDFU mode and then ran the script and it worked!
