### ISSUE TITLE
Not Working ipad2,2

### ISSUE THREAD

**Issue by cafealpha** [LukeZGD/32bit-OTA-Downgrader#25]
It doesn't work a few days ago.

iOS 8.4.1 Downgrade
[Log] Saving 8.4.1 blobs with tsschecker...
Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[TSSC] manually specified ecid to use, parsed "919124589996" to dec:919124589996 hex:d600183dac
[TSSC] opening resources/manifests/BuildManifest_iPad2,2_8.4.1.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
​
iOS 8.4.1 for device iPad2,2 IS NOT being signed!
ls: '*_iPad2,2_8.4.1-*.shsh2'에 접근할 수 없습니다: 그런 파일이나 디렉터리가 없습니다
[Error] Saving 8.4.1 blobs failed. Please run the script again
It is also possible that 8.4.1 for iPad2,2 is no longer signed
​​

**Comment by LukeZGD** [comment]
6.1.3 and 8.4.1 on iPad2,2 is no longer being signed by Apple
