### ISSUE TITLE
Need Help Thanks!  tmp/pwnediBSS: No such file or directory

### ISSUE THREAD

**Issue by xiaominglei001** [LukeZGD/32bit-OTA-Downgrader#26]
this is the code
```


******* 32bit-OTA-Downgrader *******
    Downgrade script by LukeZGD     

Main Menu

HardwareModel: n94ap
ProductType: iPhone4,1
ProductVersion: 9.3.5
UniqueChipID (ECID): 748767470536

[Input] Select an option:
1) Downgrade device		 4) (Re-)Install Dependencies
2) Save OTA blobs		 5) (Any other key to exit)
3) Just put device in kDFU mode
#? 1
[Input] Select iOS version:
1) iOS 8.4.1
2) iOS 6.1.3
3) Other
4) Back
#? 2
iOS 6.1.3 Downgrade
[Log] Saving 6.1.3 blobs with tsschecker...
Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[TSSC] manually specified ecid to use, parsed "748767470536" to dec:748767470536 hex:ae5604e3c8
[TSSC] opening resources/manifests/BuildManifest_iPhone4,1_6.1.3.plist
[WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
Saved shsh blobs!

iOS 6.1.3 for device iPhone4,1 IS being signed!
[Log] Successfully saved 6.1.3 blobs.
[Log] Verifying IPSW...
[Log] Extracting iBSS from IPSW...
Archive:  iPhone4,1_6.1.3_10B329_Restore.ipsw
caution: filename not matched:  Firmware/dfu/iBSS.n94.RELEASE.dfu
[Log] Downloading iBSS...
resources/tools/pzb_linux: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by resources/tools/pzb_linux)
mv: cannot stat 'iBSS.n94.RELEASE.dfu': No such file or directory
[Log] Decrypting iBSS...
[Log] IV = 147cdef921ed14a5c10631c5e6e02d1e
[Log] Key = 6ea1eb62a9f403ee212c1f6b3039df093963b46739c6093407190fe3d750c69c
error: cannot open template
dd: failed to open 'tmp/iBSS.dec': No such file or directory
[Log] Patching iBSS...
bspatch: tmp/iBSS.dec2: No such file or directory
Make sure SSH is installed and working on the device!
Please enter Wi-Fi IP address of device for SSH connection
[Input] IP Address: 192.168.43.53
[Log] Coonecting to device via SSH... Please enter root password when prompted (default is 'alpine')
[Log] Copying stuff to device...
root@192.168.43.53's password: 
kloader                                                                                                                                                                                                    100%   51KB  50.8KB/s   00:00    
tmp/pwnediBSS: No such file or directory
[Error] Cannot connect to device via SSH.
Please check your ~/.ssh/known_hosts file and try again



```

**Comment by xiaominglei001** [comment]
> this is the code
> 
> ```
> 
> 
> ******* 32bit-OTA-Downgrader *******
>     Downgrade script by LukeZGD     
> 
> Main Menu
> 
> HardwareModel: n94ap
> ProductType: iPhone4,1
> ProductVersion: 9.3.5
> UniqueChipID (ECID): 748767470536
> 
> [Input] Select an option:
> 1) Downgrade device		 4) (Re-)Install Dependencies
> 2) Save OTA blobs		 5) (Any other key to exit)
> 3) Just put device in kDFU mode
> #? 1
> [Input] Select iOS version:
> 1) iOS 8.4.1
> 2) iOS 6.1.3
> 3) Other
> 4) Back
> #? 2
> iOS 6.1.3 Downgrade
> [Log] Saving 6.1.3 blobs with tsschecker...
> Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
> [TSSC] manually specified ecid to use, parsed "748767470536" to dec:748767470536 hex:ae5604e3c8
> [TSSC] opening resources/manifests/BuildManifest_iPhone4,1_6.1.3.plist
> [WARNING] [TSSC] could not get id0 for installType=Erase. Using fallback installType=Update since user did not specify installType manually
> [TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
> [TSSR] Sending TSS request attempt 1... success
> Saved shsh blobs!
> 
> iOS 6.1.3 for device iPhone4,1 IS being signed!
> [Log] Successfully saved 6.1.3 blobs.
> [Log] Verifying IPSW...
> [Log] Extracting iBSS from IPSW...
> Archive:  iPhone4,1_6.1.3_10B329_Restore.ipsw
> caution: filename not matched:  Firmware/dfu/iBSS.n94.RELEASE.dfu
> [Log] Downloading iBSS...
> resources/tools/pzb_linux: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by resources/tools/pzb_linux)
> mv: cannot stat 'iBSS.n94.RELEASE.dfu': No such file or directory
> [Log] Decrypting iBSS...
> [Log] IV = 147cdef921ed14a5c10631c5e6e02d1e
> [Log] Key = 6ea1eb62a9f403ee212c1f6b3039df093963b46739c6093407190fe3d750c69c
> error: cannot open template
> dd: failed to open 'tmp/iBSS.dec': No such file or directory
> [Log] Patching iBSS...
> bspatch: tmp/iBSS.dec2: No such file or directory
> Make sure SSH is installed and working on the device!
> Please enter Wi-Fi IP address of device for SSH connection
> [Input] IP Address: 192.168.43.53
> [Log] Coonecting to device via SSH... Please enter root password when prompted (default is 'alpine')
> [Log] Copying stuff to device...
> root@192.168.43.53's password: 
> kloader                                                                                                                                                                                                    100%   51KB  50.8KB/s   00:00    
> tmp/pwnediBSS: No such file or directory
> [Error] Cannot connect to device via SSH.
> Please check your ~/.ssh/known_hosts file and try again
> ```

I have install openssh，and iPhone and lubuntu within the same wifi.

**Comment by LukeZGD** [comment]
What distro are you using? Also try reinstalling dependencies

**Comment by xiaominglei001** [comment]
OK
