### ISSUE TITLE
Not working on macOS 10.15.2

### ISSUE THREAD

**Issue by CodeyMoore** [LukeZGD/32bit-OTA-Downgrader#3]
The tool isnt working for me, its just wanting to install the dependencies.

**Comment by LukeZGD** [comment]
Updated for 77a4c51a9eedba9ea48a5fee9c715954106ef9c5, worked around this by putting ifuse as dependency for 10.x downgrades only, as it is still needed for that, SSH is not reliable on iOS 10. Also I won't be supporting the macOS dependency install script anymore as I can't test it, but I left it in with a message prompt
