### ISSUE TITLE
Did not work on virtualbox installed utunbu 64

### ISSUE THREAD

**Issue by chienerp** [LukeZGD/32bit-OTA-Downgrader#5]
It stuck on DFU mode, I tried many times

**Comment by chienerp** [comment]
pressed Enter once to let it recognize as well

**Comment by chienerp** [comment]
![Untitled](https://user-images.githubusercontent.com/61206067/75173495-8a2ef980-5761-11ea-9f7f-6c03c1149584.png)

**Comment by LukeZGD** [comment]
Do you have your device connected to the virtual machine USB? Also do you have a USB filter in your VM as well? 

This doesn't seem to be an issue in the code, so I may close this

**Comment by chienerp** [comment]
Yep I added new usb filter for Apple and it opened automatically apple notification in virtualbox as I plug in

**Comment by LukeZGD** [comment]
I don't think I can help when it comes to VMs, but has it worked in other methods like live USB?

**Comment by chienerp** [comment]
The script worked great in Ubuntu 16.04 tks you so much mate

**Comment by bb2020** [comment]
vendorid=0x05ac,productid=0x12a0
vendorid=0x05ac,productid=0x1227
vendorid=0x05ac,productid=0x1281

**Comment by bb2020** [comment]
Try passing these to VM
vendorid=0x05ac,productid=0x12a0
vendorid=0x05ac,productid=0x1227
vendorid=0x05ac,productid=0x1281
