### ISSUE TITLE
problem about install ipsw

### ISSUE THREAD

**Issue by riverinem** [LukeZGD/32bit-OTA-Downgrader#9]
the following code comes to me when I have downloaded the ipsw, so what does it mean? Thank you~

`iOS 6.1.3 for device iPhone4,1 IS being signed!

cp: iPhone4,1_6.1.3_10B329_Restore/Firmware/dfu/iBSS.n94ap.RELEASE.dfu: No such file or directory
[Error] pzb not found! Depends on partialZipBrowser: https://github.com/tihmstar/partialZipBrowser
tian@MacBook-Pro 32bit-OTA-Downgrader-master % 
`

**Comment by LukeZGD** [comment]
Please try again with the latest commit, it was just a 1 line error

**Comment by LukeZGD** [comment]
Tested it myself, it should work now
